version: "3.7"

services:
  app:
    build: .
    ports:
      - "8090:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: navin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: telusko
    ports:
      - 5433:5432
